### ISSUE TITLE
Drawings and Paint Programs

### ISSUE THREAD

**Issue by BlueMints000** [Plippo/touchscreen-tools#2]
Hello! Will this work for Art Programs like Gimp?  I'm a Graphic Designer and I like to paint, and I do 3D Modeling work too.  I have Kubuntu 20.

**Comment by Plippo** [comment]
Unfortunately this project has not been maintained in the last 8 years and probably doesn't work anymore.

**Comment by BlueMints000** [comment]
Ok, Thank you.

**Comment by BlueMints000** [comment]
Ok, thank you, thank you for letting me know.
